version: "3.7"

services:
    # image project
    app:
        container_name: fabioribeiroclm-laravel-9
        build:
            context: ./
            dockerfile: Dockerfile
<<<<<<< HEAD
        image: fabioribeiroclm/laravel9-ead-admin
=======
        image: especializati/laravel9-app
>>>>>>> parent of 7266c5b... Merge branch 'main' of https://github.com/fabiohkd/dashboard-ead into main
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-9

    # nginx
    nginx:
        container_name: fabioribeiroclm-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-9

    # db mysql
    mysql:
<<<<<<< HEAD
        container_name: fabioribeiroclm-mysql
        image: mysql:8.0
        restart: always
        command: --authentication_policy=mysql_native_password
=======
        container_name: ead-mysql
        image: mysql:5.7.22
        restart: unless-stopped
>>>>>>> parent of 7266c5b... Merge branch 'main' of https://github.com/fabiohkd/dashboard-ead into main
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel-9

    # queue
    queue:
<<<<<<< HEAD
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: fabioribeiroclm-queue
        image: fabioribeiroclm/laravel9-ead-admin
=======
        container_name: ead-queue
        image: especializati/laravel9-app
>>>>>>> parent of 7266c5b... Merge branch 'main' of https://github.com/fabiohkd/dashboard-ead into main
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel-9

    # redis
    redis:
        container_name: fabioribeiroclm-redis
        image: redis:latest
        networks:
            - laravel-9

networks:
    laravel-9:
        driver: bridge
