version: "3.8"

services:
    # image project
    app:
        container_name: ead-laravel-9
        build:
            context: .
            dockerfile: Dockerfile
        image: fabioribeiroclm/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - queue
        networks:
            - laravel-network

    # nginx
    nginx:
        container_name: ead-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-network

    # db mysql
    mysql:
        container_name: ead-mysql
        image: mysql:8.0.28
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel-network

    # queue
    queue:
        container_name: ead-queue
        image: fabioribeiroclm/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel-network

    # redis
    redis:
        container_name: ead-redis
        image: redis:latest
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
